name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'World'
      select:
        description: 'Select a value'
        type: choice
        required: true
        default: 'Option 1'
        options:
          - 'option1'
          - 'option2'

env:
  SELECT_VALUE: "{'option1': 'value1', 'option2': 'value2'}[${{ github.event.inputs.select }}]"

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, ${{ github.event.inputs.name }}!"
      - name: Select
        run: echo "${{ env.SELECT_VALUE }}!"
