name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'World'
      select:
        description: 'Select a value'
        type: choice
        required: true
        default: 'Option 1'
        options:
          - 'Option 1'
          - 'Option 2'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, ${{ github.event.inputs.name }}!"
      - name: Select
        run: echo "${{ github.event.inputs.select }}!"
